// Code generated by mockery. DO NOT EDIT.

package mock

import (
	"github.com/thep2p/skipgraph-go/core/model"
	"github.com/thep2p/skipgraph-go/core/types"
	"github.com/stretchr/testify/mock"
)

// ImmutableLookupTable is an autogenerated mock type for the ImmutableLookupTable type
type ImmutableLookupTable struct {
	mock.Mock
}

type ImmutableLookupTable_Expecter struct {
	mock *mock.Mock
}

func (_m *ImmutableLookupTable) EXPECT() *ImmutableLookupTable_Expecter {
	return &ImmutableLookupTable_Expecter{mock: &_m.Mock}
}

// AddEntry provides a mock function with given fields: dir, level, identity
func (_m *ImmutableLookupTable) AddEntry(dir types.Direction, level types.Level, identity model.Identity) error {
	ret := _m.Called(dir, level, identity)

	if len(ret) == 0 {
		panic("no return value specified for AddEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Direction, types.Level, model.Identity) error); ok {
		r0 = rf(dir, level, identity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEntry provides a mock function with given fields: dir, lev
func (_m *ImmutableLookupTable) GetEntry(dir types.Direction, lev types.Level) (*model.Identity, error) {
	ret := _m.Called(dir, lev)

	if len(ret) == 0 {
		panic("no return value specified for GetEntry")
	}

	var r0 *model.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Direction, types.Level) (*model.Identity, error)); ok {
		return rf(dir, lev)
	}
	if rf, ok := ret.Get(0).(func(types.Direction, types.Level) *model.Identity); ok {
		r0 = rf(dir, lev)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Direction, types.Level) error); ok {
		r1 = rf(dir, lev)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImmutableLookupTable_AddEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEntry'
type ImmutableLookupTable_AddEntry_Call struct {
	*mock.Call
}

// AddEntry is a helper method to define mock.On call
//   - dir types.Direction
//   - level types.Level
//   - identity model.Identity
func (_e *ImmutableLookupTable_Expecter) AddEntry(dir interface{}, level interface{}, identity interface{}) *ImmutableLookupTable_AddEntry_Call {
	return &ImmutableLookupTable_AddEntry_Call{Call: _e.mock.On("AddEntry", dir, level, identity)}
}

func (_c *ImmutableLookupTable_AddEntry_Call) Run(run func(dir types.Direction, level types.Level, identity model.Identity)) *ImmutableLookupTable_AddEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Direction), args[1].(types.Level), args[2].(model.Identity))
	})
	return _c
}

func (_c *ImmutableLookupTable_AddEntry_Call) Return(_a0 error) *ImmutableLookupTable_AddEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImmutableLookupTable_AddEntry_Call) RunAndReturn(run func(types.Direction, types.Level, model.Identity) error) *ImmutableLookupTable_AddEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ImmutableLookupTable_GetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntry'
type ImmutableLookupTable_GetEntry_Call struct {
	*mock.Call
}

// GetEntry is a helper method to define mock.On call
//   - dir types.Direction
//   - lev types.Level
func (_e *ImmutableLookupTable_Expecter) GetEntry(dir interface{}, lev interface{}) *ImmutableLookupTable_GetEntry_Call {
	return &ImmutableLookupTable_GetEntry_Call{Call: _e.mock.On("GetEntry", dir, lev)}
}

func (_c *ImmutableLookupTable_GetEntry_Call) Run(run func(dir types.Direction, lev types.Level)) *ImmutableLookupTable_GetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Direction), args[1].(types.Level))
	})
	return _c
}

func (_c *ImmutableLookupTable_GetEntry_Call) Return(_a0 *model.Identity, _a1 error) *ImmutableLookupTable_GetEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ImmutableLookupTable_GetEntry_Call) RunAndReturn(run func(types.Direction, types.Level) (*model.Identity, error)) *ImmutableLookupTable_GetEntry_Call {
	_c.Call.Return(run)
	return _c
}

// NewImmutableLookupTable creates a new instance of ImmutableLookupTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImmutableLookupTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImmutableLookupTable {
	mock := &ImmutableLookupTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
